name: Build LaTeX Document
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  build-latex-document:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Github Action for LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          latexmk_use_xelatex: true
      - name: Save result
        uses: actions/upload-artifact@v3
        with:
          name: document
          path: main.pdf
